### ISSUE TITLE
provide run option without database to just develop the template

### ISSUE THREAD

**Issue by PeterTheOne** [AKVorrat/ueberwachungspaket.at#16]

**Comment by PeterTheOne** [comment]
This line https://github.com/AKVorrat/ueberwachungspaket.at/blob/master/ueberwachungspaket/__init__.py#L9 needs to be disabled..

**Comment by PublicScam** [comment]
I guess it would be just fine to allow for SQLite usage in place of MySQL.

**Comment by PeterTheOne** [comment]
For local testing of just the templates, I didn't need any database at all ^^

**Comment by socialhack** [comment]
I would also be a user for this feature.

**Comment by PublicScam** [comment]
@PeterTheOne @socialhack Please test this patch on your OS.
