### ISSUE TITLE
new representative selector "key players" 

### ISSUE THREAD

**Issue by socialhack** [AKVorrat/ueberwachungspaket.at#30]
In the early stages of the discussion it will be vital to convince the main representatives in charge of the dossier. Hence it makes sense to define a "key players" group (translation "thematisch zuständige" ), its alternative is "all representatives" (translation: "alle abgeordneten"). The UI Element should be above the current UI for party selection. This group should be pre selected per default when a user visits /politiker/ and it shall also be weighted so to put random calls to this group more likely then others. We define the group with a json file. This should not be confused with the representatives that we display on the main page (Politiker Auslage).

**Comment by PublicScam** [comment]
@socialhack Please provide a full list of key players.

**Comment by PublicScam** [comment]
First you wanted to generalize the page by using "Politiker", now you're using "Abgeordnete" again.

**Comment by socialhack** [comment]
list is provided with important flags. wording can be changes. 

please use only the important group in case 00000 and call reminder picks a politician.
