### ISSUE TITLE
Bsp. Dialog für Politiker Anruf

### ISSUE THREAD

**Issue by socialhack** [AKVorrat/ueberwachungspaket.at#41]
auf representative.html unter Zeile 60. 
Gestaltung so wie Politiker Dialog auf Startseite
Q linksbündig, Logo der Partei
A rechtsbündig, [blank user avatar](https://regionalseminars.od.nih.gov/baltimore2016/wp-content/uploads/2015/03/user_avatar-212x212.jpg )

Q: Hallo, Sie sprechen mit dem Parlamentsklub von ({{ rep.party.shortname }}). 
A: Guten Tag, meine Name ist <your name here> ich würde gerne mit {{ rep.fullname() }}  sprechen.
Q: Der ist gerade leider nicht da, kann ich ihr/ihm etwas ausrichten?
A: Ja, bitte fragen Sie sie/ihn, wie das neue Überwachungspaket uns sicherer machen wird und dass ich als normaler Bürger sehr besorgt bin über diese Ausweitung des Überwachungsstaats. 
Q: Danke. Ich werde es weiter geben. 
A: Vielen Dank für das Gespräch! Ich würde mich sehr über eine Antwort per E-Mail oder einen Rückruf freuen.

**Comment by sqrt2** [comment]
I have a commit for this prepared, however the "Parlamentsklub" text doesn't fit in case people are calling members of the government. Which text should we use in this case?

**Comment by socialhack** [comment]
The alternative for government officials would be "Büro".
