### ISSUE TITLE
example conversation of representative page should only be visible in case telephone tool is visible (MP has number)

### ISSUE THREAD

**Issue by socialhack** [AKVorrat/ueberwachungspaket.at#47]
see this edge case her: https://xn--berwachungspaket-izb.at/p/georg-vetter/

**Comment by sqrt2** [comment]
This is already the case, only that in case the representative is a member of a party group, their number is assumed to be the parliamentary group's number, see [models.py:202](https://github.com/AKVorrat/ueberwachungspaket.at/blob/master/database/models.py#L202).

**Comment by socialhack** [comment]
So this MP should have a call tool for his party. Why is this not visible? 
If what you describe is expected behaviour for MPs with a party, the edge case I brought up should still be fixed for MPs without parties?

**Comment by sqrt2** [comment]
What do you mean? The representative you've linked is member of a party and shows the call tool. Representatives without a party don't have a call tool on their page. This is how the page works right now.
