### ISSUE TITLE
Replace Niko Alm with Karin Doppelbauer

### ISSUE THREAD

**Issue by PeterTheOne** [AKVorrat/ueberwachungspaket.at#53]

**Comment by PeterTheOne** [comment]
Alm wurde schon gelöscht https://github.com/AKVorrat/ueberwachungspaket.at/commit/870b719473a8774d82d1127135650778b78f56ea aber Doppelbauer noch nicht hinzugefügt.

**Comment by PeterTheOne** [comment]
https://www.parlament.gv.at/WWER/PAD_91141/

**Comment by sqrt2** [comment]
We had to wait for them to add a picture, glad to see it has been added now. Issue has been fixed via 5fec24ea71d4a122ef5d5d159e3c90002d7ed2ee.
