### ISSUE TITLE
Add FB Messenger, Telegram and Whatsapp share links

### ISSUE THREAD

**Issue by PeterTheOne** [AKVorrat/ueberwachungspaket.at#6]
FB Messenger and Whatsapp only work on Mobile devices. Telegram also works on desktop. Code is in `share.html` .

Example http://ordnungswache.at/ (bottom left corner) , see: https://github.com/PPOE/ordnungswache.at/blob/gh-pages/index.html#L349-L378 and https://github.com/PPOE/ordnungswache.at/blob/gh-pages/js/script.js#L6-L8

Representatives with Facebook pages can also be contacted via FB messenger with `http://fb.com/msg/*pagename*`. Code is in `representative.html`

Example: https://ppoe.github.io/plakatemap/ "FB Messenger" , see: https://github.com/PPOE/plakatemap/blob/20ec0ccf0f16d44a10bd8a598e28e419e57a13be/index.html#L41

**Comment by PeterTheOne** [comment]
Also we could think about sms links: `<a href="sms:*number*?body=*text*">Send SMS</a>`.. But there are multiple different formats.. :/ http://stackoverflow.com/a/19126326/782920

This could help with that https://github.com/smeeckaert/sms-link

**Comment by socialhack** [comment]
cool, I want to have this!
